### PR TITLE
Add even more crawlers

### PR DESCRIPTION
**Pull request by Titaniumtown**
Makes indentation in browsers.list look nice also adding more crawlers. I'm just adding more crawlers as i see them in my logs.

### CODE REVIEW

**Comment by Titaniumtown** [comment]
weird, seems like my fixes w/ the indentation is lost when i pushed it to github, strange.

**Comment by Titaniumtown** [comment]
@allinurl does this look good to you?

**Comment by Titaniumtown** [comment]
Bump, would love for this to be merged!

**Comment by allinurl** [comment]
Merged. Thank you!

**Comment by Titaniumtown** [comment]
If i find any more, I'll be sure to make a PR!

**Pull request merged**
