### PR TITLE
Add valid_output_type() to validate the filename given via '-o'

### PR DESCRIPTION
**Pull request by TerraTech**
fixes allinurl/goaccess#901

### CODE REVIEW

**Comment by TerraTech** [comment]
Minor fix was force pushed.  PR is stable now.

**Comment by TerraTech** [comment]
sigh - I need to make a minor fix, '-o' != '-f'

**Comment by TerraTech** [comment]
Minor fix has been force pushed.  PR is ready to merge.

**Comment by allinurl** [comment]
Merged. This is great! Thank you!

**Pull request merged**
