### PR TITLE
Make HTML report logo and link changeable via configuration options

### PR DESCRIPTION
**Pull request by ottok**

### CODE REVIEW

**Comment by allinurl** [comment]
@ottok Thanks for collaborating. I really appreciate this PR. 

However, since v1.0 is going out this week and because a lot of stuff changed in the report, there's no longer the goaccess logo. The new report features the ability to have your own custom css/js file. So that should give the option to modify the document as needed. Though, I'll be glad to merge changes once v1.0 is released :)

**Comment by allinurl** [comment]
I'm truly sorry for the time spent on that. I actually had the branch up there since [**February**](https://github.com/allinurl/goaccess/issues/223#issuecomment-187001547), I removed it this week since I'm pushing everything out pretty soon.

**Comment by ottok** [comment]
I actually read issue 223 some days ago. The issue is open and not a single commit is referenced, so it is hard to tell if any actual work has been done on it.

When I checked out the codebase on Saturday, there was only a single master branch and only one output.c that produced the log, so I could not know I need to patch something else.

We'll.. the positive side is that I've now spent time learning your codebase, so next contribution will be easier.

**Comment by allinurl** [comment]
My bad :( I'll make sure next time major releases are managed properly. Stay tuned for this week's big release!

**Pull request closed without merging**
