### PR TITLE
Replace select(2) with poll(2)

### PR DESCRIPTION
**Pull request by rsmarples**
poll(2) is more modern, more efficient and a lot faster than
select(2). The trade-off is that we need to manage the
array of struct pollfd we send it a bit more intelligently
than just manipulating tables before each call to select(2).

This commit adds functions to dynamically resize the allocation
needed when new fd's need to be monitored or old ones discarded
and then sprinkles them where needed.

### CODE REVIEW

**Comment by allinurl** [comment]
Thanks for submitting this. I'm still looking at the changes. Though, would you be able to run it through valgrind, so far I'm getting several Invalid reads on my end, wondering if you are seeing the same on your side? Thank you!

```
==24092== Memcheck, a memory error detector
==24092== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==24092== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==24092== Command: ./goaccess - -o /home/gerardoj/www/goaccess/a.html --real-time-html
==24092== Parent PID: 19780
==24092== 
==24092== Thread 2:
==24092== Invalid read of size 4
==24092==    at 0x165F69: ws_start (websocket.c:2759)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Address 0x50d7fc0 is 32 bytes inside a block of size 40 free'd
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Block was alloc'd at
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092== 
==24092== Invalid read of size 4
==24092==    at 0x165FA8: ws_start (websocket.c:2765)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Address 0x50d7fc0 is 32 bytes inside a block of size 40 free'd
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Block was alloc'd at
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092== 
==24092== Invalid read of size 4
==24092==    at 0x165FE1: ws_start (websocket.c:2769)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Address 0x50d7fc0 is 32 bytes inside a block of size 40 free'd
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Block was alloc'd at
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092== 
==24092== Invalid read of size 4
==24092==    at 0x166028: ws_start (websocket.c:2773)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Address 0x50d7fc0 is 32 bytes inside a block of size 40 free'd
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Block was alloc'd at
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092== 
==24092== Invalid read of size 2
==24092==    at 0x166058: ws_start (websocket.c:2779)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Address 0x50d7fc6 is 38 bytes inside a block of size 40 free'd
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Block was alloc'd at
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092== 
==24092== Invalid read of size 2
==24092==    at 0x16609D: ws_start (websocket.c:2786)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Address 0x50d7fc6 is 38 bytes inside a block of size 40 free'd
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092==  Block was alloc'd at
==24092==    at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==24092==    by 0x16670A: xrealloc (xmalloc.c:80)
==24092==    by 0x15FB5A: set_pollfd (websocket.c:199)
==24092==    by 0x1615F1: accept_client (websocket.c:1037)
==24092==    by 0x1640CB: handle_accept (websocket.c:2194)
==24092==    by 0x166051: ws_start (websocket.c:2776)
==24092==    by 0x13955C: start_server (gwsocket.c:335)
==24092==    by 0x4C57FA2: start_thread (pthread_create.c:486)
==24092==    by 0x4D6A4CE: clone (clone.S:95)
==24092== 
==24092== 
==24092== HEAP SUMMARY:
==24092==     in use at exit: 8 bytes in 1 blocks
==24092==   total heap usage: 51,324 allocs, 51,323 frees, 21,539,333 bytes allocated
==24092== 
==24092== LEAK SUMMARY:
==24092==    definitely lost: 0 bytes in 0 blocks
==24092==    indirectly lost: 0 bytes in 0 blocks
==24092==      possibly lost: 0 bytes in 0 blocks
==24092==    still reachable: 8 bytes in 1 blocks
==24092==         suppressed: 0 bytes in 0 blocks
==24092== Reachable blocks (those to which a pointer was found) are not shown.
==24092== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==24092== 
==24092== For counts of detected and suppressed errors, rerun with: -v
==24092== ERROR SUMMARY: 75 errors from 6 contexts (suppressed: 0 from 0)
```

**Comment by rsmarples** [comment]
I'll find some time for this.
We don't have valgrind on NetBSD, but we do have the LLVM address sanitisers in our toolchain, it's just problematic when the host box lacks the compiler.

**Comment by allinurl** [comment]
I'll take a look at it as well and see what I find. Thanks again!

**Comment by rsmarples** [comment]
PR #1993 is required as the first stepping stone to get address sanitisation to work via the clang compiler.
Another PR will follow to fix a issue compiling it specific to NetBSD.

**Comment by rsmarples** [comment]
Should be fixed now.

**Comment by allinurl** [comment]
Merged. Thanks again for fixing this and submitting this PR. I added a fix (https://github.com/allinurl/goaccess/commit/98d694791c562b79962bd8834e3c85bdf26f3db1) for a leak on the last fdstate. Let me know if it makes sense adding that free call at point.

**Comment by rsmarples** [comment]
> Merged. Thanks again for fixing this and submitting this PR. I added a fix ([98d6947](https://github.com/allinurl/goaccess/commit/98d694791c562b79962bd8834e3c85bdf26f3db1)) for a leak on the last fdstate. Let me know if it makes sense adding that free call at point.

So that means that an fd being monitored wasn't closed.
[If all fd's being monitored are closed then fdstate is already freed here](https://github.com/allinurl/goaccess/blob/master/src/websocket.c#L220)

Working out which fd isn't being closed and ensuring it is would be the cleaner approach if you feel that's important.
Your's at least is the safety net.

If you ever have plans to open anothe websocket afterwards, you might want to set vars to NULL after freeing them, especially static ones such as fdstate.
Otherwise I'm fine with it :)

**Comment by allinurl** [comment]
I see what you mean, yeah it's definitely not a biggie as it appears it was only upon stopping the server, though, mostly so it doesn't raise any flags on my tests :) I just added a minor commit to NULL in case we ever need to restart it.

**Pull request merged**
