### PR TITLE
Several issues found by Coverity

### PR DESCRIPTION
**Pull request by cgzones**
This might also be a copy-paste-error (the second `headers->upgrade`):
https://github.com/allinurl/goaccess/blob/88dc6c2a5d842bedac3c59760bff89305c10e78b/src/websocket.c#L1473-L1477

### CODE REVIEW

**Comment by allinurl** [comment]
Thanks a lot for submitting this PR. For some reason I didn't get any notifications of recent changes. I pretty much just noticed all these. Let me take a look at them and I'll get back to you.

**Review by allinurl — CHANGES_REQUESTED** [review]
Good point. I think commit ec2cd1e will create a leak on the second run (restore). e.g.,

    echo 'example.com:80 192.168.232.26 - - [29/May/2016:14:31:17 -0500] "GET / HTTP/1.1" 200 93854 "http://www.google.com" "Mozilla/5.0 (iPad; CPU OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1"' | valgrind --log-file=log --tool=memcheck --leak-check=full --show-leak-kinds=all ./goaccess - --restore --persist -o test.html --log-format=VCOMBINED

**Review by allinurl — APPROVED** [review]

**Review by allinurl — APPROVED** [review]

**Review by allinurl — APPROVED** [review]

**Review by allinurl — APPROVED** [review]

**Review by allinurl — APPROVED** [review]

**Review by allinurl — APPROVED** [review]

**Review by allinurl — APPROVED** [review]

**Review by allinurl — APPROVED** [review]

**Review by allinurl — APPROVED** [review]

**Review by allinurl — APPROVED** [review]

**Comment by cgzones** [comment]
> Good point. I think commit [ec2cd1e](https://github.com/allinurl/goaccess/commit/ec2cd1eef13e9efb68c8b741be6caacdea1e0d88) will create a leak on the second run (restore). e.g.,
> 
> ```
> echo 'example.com:80 192.168.232.26 - - [29/May/2016:14:31:17 -0500] "GET / HTTP/1.1" 200 93854 "http://www.google.com" "Mozilla/5.0 (iPad; CPU OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1"' | valgrind --log-file=log --tool=memcheck --leak-check=full --show-leak-kinds=all ./goaccess - --restore --persist -o test.html --log-format=VCOMBINED
> ```

Ah, the memory is not allocated by `tpl_map()`, but by `tpl_unpack()`.

**Comment by allinurl** [comment]
Merged. Thanks a lot of submitting these fixes!

**Pull request merged**
