### PR TITLE
Debian packaging files

### PR DESCRIPTION
**Pull request by szepeviktor**
Simply install dependencies and `dpkg-buildpackage -uc -us -B`

### CODE REVIEW

**Comment by allinurl** [comment]
I'm curious, is this PR meant to be a replacement for the debian [**package**](https://packages.debian.org/jessie/goaccess)? If it is, then please submit a patch directly to the maintainer listed on that page. Unfortunately I don't have access to make any updates to it.

**Comment by szepeviktor** [comment]
Thanks.

I've sent this PR to you.
To use it as the source of *your* Debian packages.

These settings make the .deb package free of lintian errors (security, size, Debian policies)
See the current report here
https://github.com/allinurl/goaccess/issues/744#issuecomment-296482356


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by allinurl** [comment]
I see. Although I do appreciate you sending this in, I won't be able to merge it since the deb repo is independent from goaccess source code. 

What I can do is to look into some of these warnings/errors in the upcoming build. However, from a quick glance to the report you posted (#744) , not all of them are applicable to a non-debian repo package.

**Comment by szepeviktor** [comment]
I see. You use an universal packaging tool.

Please consider security at least (hardening).

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by szepeviktor** [comment]
Here it is: https://github.com/szepeviktor/debian-server-tools/blob/master/package/docker-backport-goaccess.sh
Built on my backporting container. Produces .deb in /opt/results

**Comment by szepeviktor** [comment]
@allinurl Would it be possible to link my Docker-based Debian packaging script in the README?

**Comment by szepeviktor** [comment]
I prefer the official packaging data: https://packages.qa.debian.org/g/goaccess.html

Please consider preferring it yourself.

**Pull request closed without merging**
