### PR TITLE
rewrite Dockerfile

### PR DESCRIPTION
**Pull request by err931**
:warning: **This request makes destructive changes. Please verify and merge.**

Links: #1404

### CODE REVIEW

**Comment by allinurl** [comment]
Merged. Thanks very much. 

BTW, can I ask what destructive changes it does?

**Comment by err931** [comment]
> BTW, can I ask what destructive changes it does?

**I wrote to the issue, but has changed the library from OpenSSL to LibreSSL.**
There are no compatibility issues with OpenSSL, but there may be new issues that were not noticed during testing.

I think so...

**Comment by frebib** [comment]
> BTW, can I ask what destructive changes it does?
Undocumented behaviour change when the user doesn't override the CMD. This just bit me :(

**Comment by allinurl** [comment]
@err931 Could you please address @frebib question? Thanks!

**Pull request merged**
