### PR TITLE
small fix

### PR DESCRIPTION
**Pull request by err931**
- Modify I name
- Fix duplicate contributor name
- Remove Vagrantfile (Not used)

### CODE REVIEW

**Comment by err931** [comment]
Oops! Reopend.

**Comment by allinurl** [comment]
Can I ask why removing the vagrant file? Thanks

**Comment by err931** [comment]
**Of course, there is a reason for requesting deletion.**
The `Vagrantfile` has not been updated for more than three years and the base OS is an older version.

Problems that don't work may also be caused by bugs (or configuration errors) that occur from the **VirtualBox** side.
I decided to remove it because it could increase the running cost.

**Comment by allinurl** [comment]
Got it. Thanks!

**Pull request merged**
