### PR TITLE
WIP add translation with gettext

### PR DESCRIPTION
**Pull request by haricot**
I think it's a good start.
But when I replace gettext_noop(Marks the given translation for extraction and returns it unchanged) "N_" to gettext "_"

Example in src/ui.h : 
#define VISIT_LABEL N_("Visitors") to #define VISIT_LABEL _("Visitors") 

This error appears when compiling make:
Error: An element of the initialization is not a constant

The solution may be to move the initialization in the main, in the initialization function.
I do not see too much! Do you have an idea ?

Ref issues PRs:
#701 #457 #453

### CODE REVIEW

**Comment by allinurl** [comment]
This is a great start. Thank you!

I'll look into it and merge. Are you currently getting the error mentioned above with this PR? or do I need to change something to trigger it?

**Comment by haricot** [comment]
I don't have the above error in the PR.
Yes ! We need to change a somethings.

Only the translations with `_()` in the src/ui.h files are translated into the program.
With `N_()` the translations are unchanged in the program but we can start translating them with .po files.

It would be necessary that all the translations begin with `_()` instead of `N_()`, it works with some translation because it does not use the same way in the .c

Try to find out why, but it does not come.

**Comment by allinurl** [comment]
Thank a lot! I believe it should work now. Please give it a shot and let me know how it goes.

There are a few minor changes I need to do to the terminal dashboard so labels fit well, and probably bootstrap a JSON string into to the HTML document so labels in the [template file](https://github.com/allinurl/goaccess/blob/master/resources/tpls.html) get translated.

I need to check but I suspect there are still a few more string literals in the code that need to be added as `#defines` under ui.h.

**Comment by haricot** [comment]
Very good !
Your changes resolve the issue.
Other translations appear and it's really nice! :-)
Indeed, there are still things to translate.
Thank you very much !

**Pull request merged**
